Lab1/Controllers/DepositController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Lab1.Infrastucture;
using Lab1.Models;
using Lab1.Services;

namespace Lab1.Controllers
{
    public class DepositController : Controller
    {
        private readonly UserContext db = new UserContext();
        private readonly BankService bankService = new BankService();

        public ActionResult CloseBankDay()
        {
            bankService.CloseBankDay();
            return View(db.AccountOperations.ToList());
        }

        [HttpGet]
        public ActionResult CreateCredit(int id)
        {
            var deposit = new ClientDepositCredit { ClientId = id };
            ViewBag.DepositCreditId = new SelectList(db.DepositCredits, "DepositCreditId", "Name");
            return View(deposit);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCredit([Bind(Include = "ClientDepositCreditId,Number,Sum,StartDate,ClientId,DepositCreditId,MainAccountId,PersentAccountId")] ClientDepositCredit clientDepositCredit)
        {

            if (ModelState.IsValid)
            {
                var credit =
                    db.DepositCredits.FirstOrDefault(x => x.DepositCreditId == clientDepositCredit.DepositCreditId);
                var mainAccount = new Account
                {
                    AccountNumber = "9999" + Guid.NewGuid().ToString().Substring(0, 9),
                    AccountCodeId = 2,
                    Sum = clientDepositCredit.Sum,
                    CurrencyId = credit.CurrencyId,
                    AccountActivity = AccountActivity.Active,
                    AccountTypeId = 2,
                    ClientId = clientDepositCredit.ClientId
                };

                var persentAccount = new Account
                {
                    AccountNumber = "9999" + Guid.NewGuid().ToString().Substring(0, 9),
                    AccountCodeId = 2,
                    CurrencyId = credit.CurrencyId,
                    AccountActivity = AccountActivity.Active,
                    AccountTypeId = 3,
                    ClientId = clientDepositCredit.ClientId
                };

                clientDepositCredit.MainAccount = mainAccount;
                clientDepositCredit.PersentAccount = persentAccount;
                clientDepositCredit.DaysLeft = credit.DaysCount;
                clientDepositCredit.StartDate = DateTime.Now;


                var bdf = db.Accounts.FirstOrDefault();
                var exchangeRate = db.ExchangeRates.FirstOrDefault(x => x.StartCurrencyId == clientDepositCredit.DepositCredit.CurrencyId
                  && x.FinishCurrencyId == bdf.CurrencyId);

               
                bdf.Sum -= clientDepositCredit.Sum * exchangeRate.Rate;

                bdf.AccountOperations.Add(new AccountOperation
                {
                    OperationType = "Debit",
                    Sum = clientDepositCredit.Sum,
                    OperationDate = DateTime.Now,
                });

                mainAccount.AccountOperations.Add(new AccountOperation
                {
                    OperationType = "Debit",
                    Sum = clientDepositCredit.Sum,
                    OperationDate = DateTime.Now,
                });


                db.Entry(bdf).State = EntityState.Modified;
                db.SaveChanges();

                db.ClientDepositCredits.Add(clientDepositCredit);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            ViewBag.DepositCreditId = new SelectList(db.DepositCredits, "DepositCreditId", "Name", clientDepositCredit.DepositCreditId);
            return View(clientDepositCredit);
        }

        [HttpGet]
        public ActionResult CreateDeposit(int id)
        {
            var deposit = new ClientDepositCredit {ClientId = id};
            ViewBag.DepositCreditId = new SelectList(db.DepositCredits, "DepositCreditId", "Name");
            return View(deposit);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateDeposit([Bind(Include = "ClientDepositCreditId,Number,Sum,StartDate,ClientId,DepositCreditId,MainAccountId,PersentAccountId")] ClientDepositCredit clientDepositCredit)
        {

            if (ModelState.IsValid)
            {
                var deposit =
                    db.DepositCredits.FirstOrDefault(x => x.DepositCreditId == clientDepositCredit.DepositCreditId);
                var mainAccount = new Account
                {
                    AccountNumber = "9999" + Guid.NewGuid().ToString().Substring(0, 9),
                    AccountCodeId = 1,
                    Sum = clientDepositCredit.Sum,
                    CurrencyId = deposit.CurrencyId,
                    AccountActivity = AccountActivity.Passive,
                    AccountTypeId = 2,
                    ClientId = clientDepositCredit.ClientId
                };

                var persentAccount = new Account
                {
                    AccountNumber = "9999" + Guid.NewGuid().ToString().Substring(0, 9),
                    AccountCodeId = 1,
                    CurrencyId = deposit.CurrencyId,
                    AccountActivity = AccountActivity.Passive,
                    AccountTypeId = 3,
                    ClientId = clientDepositCredit.ClientId
                };

                clientDepositCredit.MainAccount = mainAccount;
                clientDepositCredit.PersentAccount = persentAccount;
                clientDepositCredit.DaysLeft = deposit.DaysCount;
                clientDepositCredit.StartDate = DateTime.Now;

                var bdf = db.Accounts.FirstOrDefault();
                var exchangeRate = db.ExchangeRates.FirstOrDefault(x => x.StartCurrencyId == clientDepositCredit.DepositCredit.CurrencyId
                  && x.FinishCurrencyId == bdf.CurrencyId);


                bdf.Sum += clientDepositCredit.Sum * exchangeRate.Rate;

                bdf.AccountOperations.Add(new AccountOperation
                {
                    OperationType = "Credit",
                    Sum = clientDepositCredit.Sum,
                    OperationDate = DateTime.Now,
                });

                mainAccount.AccountOperations.Add(new AccountOperation
                {
                    OperationType = "Debit",
                    Sum = clientDepositCredit.Sum,
                    OperationDate = DateTime.Now,
                });


                db.Entry(bdf).State = EntityState.Modified;
                db.SaveChanges();

                db.ClientDepositCredits.Add(clientDepositCredit);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            ViewBag.DepositCreditId = new SelectList(db.DepositCredits, "DepositCreditId", "Name", clientDepositCredit.DepositCreditId);
            return View(clientDepositCredit);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lab1/Views/Shared/_BankomatLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.maskedinput.js"></script>
    <link href="~/Content/Bankomat.css" rel="stylesheet" type="text/css"/>

    <title>_BankomatLayout</title>
</head>
<body>
    <div class="container">
        <div class="main-window">
            <div class="col-lg-2 left"></div>
            <div class="col-lg-8 center">
                @RenderBody()
            </div>
            <div class="col-lg-2 right">
                <img class="img-responsive" src="../../Content/card1.jpg" />
                <img class="img-responsive" src="../../Content/card2.jpg" />
                <img class="img-responsive" src="../../Content/card3.jpg" />
            </div>
        </div>
    </div>

</body>
</html>

Lab1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.maskedinput.js"></script>
</head>
<body>
    <div class="row head-block">
    </div>
<div class="navbar navbar-inverse">
    <div class="">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("All clients", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Close bank day", "CloseBankDay", "Deposit", new { area = "" }, new { @class = "navbar-brand" })</li>
            </ul>
        </div>
    </div>
</div>

<div class="">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>


<script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>