Lab1/Models/ViewModels/RequestedMoney.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Lab1.Models.ViewModels
{
    public class RequestedMoney
    {
        [Required(ErrorMessage = "Enter balance!")]
        [Range(0, Int32.MaxValue, ErrorMessage = "Incorrect value!")]
        public int Money { get; set; }
    }
}

Lab1/Controllers/BankomatController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Lab1.Infrastucture;
using Lab1.Models;
using Lab1.Models.ViewModels;

namespace Lab1.Controllers
{
    public class BankomatController : Controller
    {
        private readonly UserContext _db = new UserContext();
        private static Card currentCard;

        // GET: Bankomat
        [HttpGet]
        public ActionResult Index()
        {
            return View(new Card());
        }

        [HttpGet]
        public ActionResult ContinueWork()
        {
            var tmp = currentCard;
            tmp = currentCard;
            return View("Index", tmp);
        }

        [HttpPost]
        public ActionResult Index(Card card)
        {
            if (ModelState.IsValid)
            {
                var cardFromDb = _db.Set<ClientCard>().FirstOrDefault(x => x.ClientCardNumber == card.CardNumber);
                if (cardFromDb == null)
                {
                    ModelState.AddModelError("", "Incorrect card number!");
                }
                else
                {
                    if (card.AttemptionsCount == 1)
                    {
                        ModelState.AddModelError("", "Your card will be blocked! You have the last attemption!");
                        card = new Card {CardNumber = ""};
                    }
                    else if (cardFromDb.PinCode != card.PinCode)
                    {
                        ModelState.AddModelError("",
                            $"Incorrect pin code! You have {card.AttemptionsCount} attemptions!");
                        card.AttemptionsCount--;
                    }
                    else
                    {
                        currentCard = card;
                        return RedirectToAction("Menu");
                    }
                }
            }
            return View(card);
        }

        [HttpGet]
        public ActionResult Menu()
        {
            return View();
        }


        [HttpGet]
        public ActionResult GetMoney()
        {
            if (currentCard == null)
            {
                return View("Index", new Card());
            }

            return View("RequestedMoney");
        }

        [HttpPost]
        public ActionResult GetMoney(RequestedMoney model)
        {
            if (currentCard == null)
            {
                return View("Index", new Card());
            }
            var card = _db.ClientCards.FirstOrDefault();
            var account = card?.Account;
            var balance = account.Sum;
            if (model.Money > balance)
            {
                ModelState.AddModelError("", "There is no so much monet!");
            }

            if (ModelState.IsValid)
            {
                //Decrease balance in db, check balance
                account.Sum = account.Sum - (decimal)model.Money;
                
                _db.Entry(account).State = EntityState.Modified;
                _db.SaveChanges();

                return View("GetMoneySuccessMessage");
            }
          
            return View("RequestedMoney", model);
        }

        [HttpGet]
        public ActionResult Balance()
        {
            if (currentCard == null)
            {
                return View("Index", new Card());
            }
            //Get balance from db
            var balance = _db.ClientCards.FirstOrDefault()?.Account?.Sum;
           
            return View(balance.Value);
        }

        [HttpGet]
        public ActionResult GetCardBack()
        {
            currentCard = null;
            return View("Index", new Card {PinCode = 0});
        }

    }
}

Lab1/Views/Bankomat/Balance.cshtml
@model decimal
@{
    ViewBag.Title = "Balance";
    Layout = "~/Views/Shared/_BankomatLayout.cshtml";
}


<div class="custom-container text-center">
    <div class="panel panel-info">
        <div class="panel-heading">Current balance</div>
        <div class="panel-body">@Model</div>
    </div>
    @Html.Partial("_AfterOperationMenu")
</div>

Lab1/Views/Bankomat/GetMoneySuccessMessage.cshtml
@{
    ViewBag.Title = "GetMoneySuccessMessage";
    Layout = "~/Views/Shared/_BankomatLayout.cshtml";
}

<div class="custom-container text-center">
    <div class="panel panel-info">
        <div class="panel-heading">Get your money ^_^</div>
    </div>
    @Html.Partial("_AfterOperationMenu")
</div>

Lab1/Views/Bankomat/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_BankomatLayout.cshtml";
}

@model Lab1.Models.ViewModels.Card

<div class="custom-container">
    @using (Html.BeginForm("Index", "Bankomat", FormMethod.Post))
    {
        <div class="form-horizontal col-lg-offset-2 col-lg-10">
            @Html.ValidationSummary(true, "", new {@class = "text-danger"})
            <div class="form-group">
                @Html.LabelFor(model => model.CardNumber, htmlAttributes: new {@class = "control-label col-md-3"})
                <div class="col-md-9">
                    @Html.EditorFor(model => model.CardNumber, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.CardNumber, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PinCode, htmlAttributes: new {@class = "control-label col-md-3"})
                <div class="col-md-9">
                    @Html.EditorFor(model => model.PinCode, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.PinCode, "", new {@class = "text-danger"})
                </div>
            </div>
            <input type="hidden" value="@Model.AttemptionsCount" name="AttemptionsCount">

            <div class="form-group">
                <div class="col-md-offset-3 col-md-9">
                    <input type="submit" value="Log in" class="btn btn-default"/>
                </div>
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $("#PinCode").mask("9999");
    });
</script>

Lab1/Views/Bankomat/Menu.cshtml
@{
    ViewBag.Title = "Menu";
    Layout = "~/Views/Shared/_BankomatLayout.cshtml";
}

<div class="custom-container text-center">
    <div class="btn-group-vertical">
        @Html.ActionLink("Get money", "GetMoney", null, new { @class = "btn btn-default btn-lg" })
        @Html.ActionLink("Get balance", "Balance", null, new { @class = "btn btn-default btn-lg" })
        @Html.ActionLink("Get card back", "GetCardBack", null, new { @class = "btn btn-default btn-lg" })
    </div>
</div>

Lab1/Views/Bankomat/RequestedMoney.cshtml
@{
    ViewBag.Title = "RequestedMoney";
    Layout = "~/Views/Shared/_BankomatLayout.cshtml";
}

@model Lab1.Models.ViewModels.RequestedMoney

<div class="custom-container">
    <div class="panel panel-info">
        <div class="panel-heading">How much money do you want?</div>
        <div class="panel-body">
            @using (Html.BeginForm("GetMoney", "Bankomat", FormMethod.Post))
            {
                <div class="form-horizontal col-lg-offset-2 col-lg-10">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Money, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Money, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                            @Html.ValidationMessageFor(model => model.Money, "", new { @class = "text-danger" })
                        </div>
                    </div>
                  
                    <div class="form-group">
                        <div class="col-md-offset-3 col-md-9">
                            <input type="submit" value="Get money" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Lab1/Views/Bankomat/_AfterOperationMenu.cshtml
<div class="custom-container text-center">
    <div class="btn-group-vertical">
        @Html.ActionLink("Continue work", "ContinueWork", null, new { @class = "btn btn-default btn-lg" })
        @Html.ActionLink("Get card back", "GetCardBack", null, new { @class = "btn btn-default btn-lg" })
    </div>
</div>